name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Protos (protoc)
        run: make proto

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make build

  node:
    if: ${{ hashFiles('dashboard/package.json') != '' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: dashboard/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Test (if present)
        run: npm test --if-present

      - name: Build (if present)
        run: npm run build --if-present


